version: "3"
services:
  backup-agent:
    image: safeplan/backup-agent:latest  

    restart: always  

    environment:
      - SAFEPLAN_ID
      - BORG_MOUNT_DATA_CACHE_ENTRIES=10 #  default is 1 which translates to 8MB, so this uses 80MB to cache access to the mounted FUSE filesystem

    volumes:
      - ${SAFEPLAN_BACKUP_DIR}:/var/safeplan/backup
      - ${SAFEPLAN_CONFIG_DIR}:/var/safeplan/config
      - ${SAFEPLAN_ONSITE_BACKUP_DIR}:/var/safeplan/repo
      - ${SAFEPLAN_WORK_DIR}:/var/safeplan/work
      - ${SAFEPLAN_HISTORY_DIR}:/var/safeplan/history
      - ${SAFEPLAN_SSH_DIR}:/root/.ssh
    ports:
      - 8080:8080  
