# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DeviceInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, initialized_at: datetime=None):  # noqa: E501
        """DeviceInfo - a model defined in Swagger

        :param id: The id of this DeviceInfo.  # noqa: E501
        :type id: str
        :param initialized_at: The initialized_at of this DeviceInfo.  # noqa: E501
        :type initialized_at: datetime
        """
        self.swagger_types = {
            'id': str,
            'initialized_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'initialized_at': 'initialized_at'
        }

        self._id = id
        self._initialized_at = initialized_at

    @classmethod
    def from_dict(cls, dikt) -> 'DeviceInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeviceInfo of this DeviceInfo.  # noqa: E501
        :rtype: DeviceInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this DeviceInfo.


        :return: The id of this DeviceInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this DeviceInfo.


        :param id: The id of this DeviceInfo.
        :type id: str
        """

        self._id = id

    @property
    def initialized_at(self) -> datetime:
        """Gets the initialized_at of this DeviceInfo.


        :return: The initialized_at of this DeviceInfo.
        :rtype: datetime
        """
        return self._initialized_at

    @initialized_at.setter
    def initialized_at(self, initialized_at: datetime):
        """Sets the initialized_at of this DeviceInfo.


        :param initialized_at: The initialized_at of this DeviceInfo.
        :type initialized_at: datetime
        """

        self._initialized_at = initialized_at
