swagger: '2.0'
info:
  version: 1.0.0
  title: backup-agent
  description: safeplan backup agent api
consumes:
  - application/json
produces:
  - application/json


host: {{ host }}
basePath: /api
schemes:
 - http
   
paths:
  /:
    get:
      tags:
      - Device
      description: returns the current status of the device
      operationId: device.get_details
      responses:
        200:
          description: All the devices
          schema:
            $ref: '#/definitions/DeviceInfo'
        400:
          description: Not initialized yet
  /mode:
    put:
      tags:
      - Device
      description: Force the device into particular mode
      operationId: device.set_mode
      parameters:
        - name: mode
          in: query
          required: true
          type: string
          enum:
            - force_backup
            - force_idle
            - default
  
      responses:
        200:
          description: All the devices
          schema:
            $ref: '#/definitions/DeviceInfo'
 
definitions:
  DeviceInfo:
    type: object
    properties:
      device_id:
        type: string
        format: uuid
        example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
      mode:
        type: string
        enum:
          - backup
          - idle
      running_process:
         type: array
         items:
           $ref: '#/definitions/RunningProcess'
      offsite_info:
        type: object
      offsite_list:
        type: object

  RunningProcess:            
    type: object
    properties:
      pid:
        type: integer
      running_since:
        type: string
        format: date-time
      type:
        type: string
        enum:
          - offsite
          - onsite
