swagger: '2.0'
info:
  version: 1.0.0
  title: backup-agent
  description: safeplan backup agent api
consumes:
  - application/json
produces:
  - application/json
paths:
  /device:
    get:
      tags:
      - Device
      description: returns the details of the device
      operationId: getDevice
      responses:
        200:
          description: All the devices
          schema:
            $ref: '#/definitions/DeviceInfo'
              
  /device/initialization:
    post:
      tags:
      - Device
      operationId: initializes the device
      parameters:
      - in: body
        name: device
        required: false
        schema:
          $ref: '#/definitions/DeviceInitializationInfo'
      responses:
        200:
          description: successfully registered device


definitions:
  DeviceInfo:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
      initialized_at:
        type: string
        format: date-time
         
  DeviceInitializationInfo:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'

        
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /safeplan/backup-agent/1.0.0
schemes:
 - https