swagger: '2.0'
info:
  version: 1.0.0
  title: backup-agent
  description: safeplan backup agent api
consumes:
  - application/json
produces:
  - application/json


host: localhost
basePath: /api
schemes:
 - http
   
paths:
  /:
    get:
      tags:
      - Device
      description: returns the current status of the device
      operationId: device.get_details
      responses:
        200:
          description: All the devices
          schema:
            $ref: '#/definitions/DeviceInfo'
        400:
          description: Not initialized yet
        

definitions:
  DeviceInfo:
    type: object
    properties:
      device_id:
        type: string
        format: uuid
        example: '0729a580-2240-11e6-9eb5-0002a5d5c51b'
      onsite_info:
        type: object
      offsite_info:
        type: object
      onsite_list:
        type: object
      offsite_list:
        type: object
              
