# coding: utf-8

"""
    device-api

    safeplan device api  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from safeplan.api_client import ApiClient


class DeviceApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def device_get_details(self, device_id, **kwargs):  # noqa: E501
        """device_get_details  # noqa: E501

        Returns the current status of the device  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.device_get_details(device_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str device_id: unique safeplan device_id (required)
        :return: StatusInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.device_get_details_with_http_info(device_id, **kwargs)  # noqa: E501
        else:
            (data) = self.device_get_details_with_http_info(device_id, **kwargs)  # noqa: E501
            return data

    def device_get_details_with_http_info(self, device_id, **kwargs):  # noqa: E501
        """device_get_details  # noqa: E501

        Returns the current status of the device  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.device_get_details_with_http_info(device_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str device_id: unique safeplan device_id (required)
        :return: StatusInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method device_get_details" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `device_get_details`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'device_id' in params:
            path_params['device_id'] = params['device_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['secret']  # noqa: E501

        return self.api_client.call_api(
            '/{device_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StatusInformation',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def device_initialize(self, device_id, initialization_information, **kwargs):  # noqa: E501
        """device_initialize  # noqa: E501

        Initialize the device  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.device_initialize(device_id, initialization_information, async=True)
        >>> result = thread.get()

        :param async bool
        :param str device_id: unique safeplan device_id (required)
        :param InitializationInformation initialization_information: (required)
        :return: StatusInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.device_initialize_with_http_info(device_id, initialization_information, **kwargs)  # noqa: E501
        else:
            (data) = self.device_initialize_with_http_info(device_id, initialization_information, **kwargs)  # noqa: E501
            return data

    def device_initialize_with_http_info(self, device_id, initialization_information, **kwargs):  # noqa: E501
        """device_initialize  # noqa: E501

        Initialize the device  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.device_initialize_with_http_info(device_id, initialization_information, async=True)
        >>> result = thread.get()

        :param async bool
        :param str device_id: unique safeplan device_id (required)
        :param InitializationInformation initialization_information: (required)
        :return: StatusInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id', 'initialization_information']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method device_initialize" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `device_initialize`")  # noqa: E501
        # verify the required parameter 'initialization_information' is set
        if ('initialization_information' not in params or
                params['initialization_information'] is None):
            raise ValueError("Missing the required parameter `initialization_information` when calling `device_initialize`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'device_id' in params:
            path_params['device_id'] = params['device_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'initialization_information' in params:
            body_params = params['initialization_information']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['secret']  # noqa: E501

        return self.api_client.call_api(
            '/{device_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StatusInformation',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def device_update_status(self, device_id, status, **kwargs):  # noqa: E501
        """device_update_status  # noqa: E501

        status  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.device_update_status(device_id, status, async=True)
        >>> result = thread.get()

        :param async bool
        :param str device_id: unique safeplan device_id (required)
        :param DeviceStatus status: (required)
        :return: StatusInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.device_update_status_with_http_info(device_id, status, **kwargs)  # noqa: E501
        else:
            (data) = self.device_update_status_with_http_info(device_id, status, **kwargs)  # noqa: E501
            return data

    def device_update_status_with_http_info(self, device_id, status, **kwargs):  # noqa: E501
        """device_update_status  # noqa: E501

        status  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.device_update_status_with_http_info(device_id, status, async=True)
        >>> result = thread.get()

        :param async bool
        :param str device_id: unique safeplan device_id (required)
        :param DeviceStatus status: (required)
        :return: StatusInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id', 'status']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method device_update_status" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `device_update_status`")  # noqa: E501
        # verify the required parameter 'status' is set
        if ('status' not in params or
                params['status'] is None):
            raise ValueError("Missing the required parameter `status` when calling `device_update_status`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'device_id' in params:
            path_params['device_id'] = params['device_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'status' in params:
            body_params = params['status']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['secret']  # noqa: E501

        return self.api_client.call_api(
            '/{device_id}/status', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StatusInformation',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
